pnpm eslint --fix src/components/LessonViewer/blocks/ImageBlockViewer.tsx
pnpm eslint --fix src/components/LessonViewer/blocks/FileBlockViewer.tsx
pnpm eslint --fix src/components/LessonViewer/ProgressReporter.tsx
pnpm eslint --fix src/components/LessonViewer/MultiBlockViewer.tsx
pnpm eslint --fix src/components/LessonViewer/BlockRenderer.tsx
pnpm eslint --fix src/components/CourseOverview/index.ts
pnpm eslint --fix src/components/CourseBuilder/index.ts
pnpm eslint --fix src/components/Classroom/AssignCourseModal.tsx
pnpm eslint --fix src/components/AttemptDetailModal.tsx
pnpm eslint --fix src/app/queryClient.ts
