-- =============================================================================
-- dev_seed_content.sql — Fase 0.5 richer content for SMA Nusantara Dev
-- =============================================================================
-- Runs AFTER dev_seed.sql. Splits "body" data (courses, subjects, curriculum,
-- assignments, attendance, invoices, P5) from "skeleton" data (users, rombel,
-- enrollments) so the base seed stays small and reviewable.
--
-- Invariants:
--   - idempotent (ON CONFLICT guards everywhere)
--   - deterministic IDs via dev_seed_uuid(label) so diffs are stable across
--     re-runs
--   - scoped to tenant slug 'sma-nusantara-dev'; purged by dev_seed_purge()

BEGIN;

-- ─── 0. Guard + helpers ──────────────────────────────────────────────────────
DO $$
DECLARE v_tenant_id uuid;
BEGIN
  SELECT id INTO v_tenant_id FROM public.tenants WHERE slug='sma-nusantara-dev';
  IF v_tenant_id IS NULL THEN
    RAISE EXCEPTION 'dev_seed_content.sql: base dev_seed.sql must run first';
  END IF;
END $$;

-- ─── 1. Academic year 2026/2027 ──────────────────────────────────────────────
INSERT INTO public.academic_years (id, tenant_id, label, starts_on, ends_on, status)
VALUES (
  public.dev_seed_uuid('ay:2026-2027'),
  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
  '2026/2027',
  DATE '2026-07-15',
  DATE '2027-06-30',
  'active'
)
ON CONFLICT (id) DO NOTHING;

-- ─── 2. Grade levels (SMA: X, XI, XII) ───────────────────────────────────────
INSERT INTO public.grade_levels (id, tenant_id, code, label, school_band, sort_order)
VALUES
  (public.dev_seed_uuid('grade:X'),   public.dev_seed_uuid('tenant:sma-nusantara-dev'), 'X',   'Kelas X',   'SMA', 10),
  (public.dev_seed_uuid('grade:XI'),  public.dev_seed_uuid('tenant:sma-nusantara-dev'), 'XI',  'Kelas XI',  'SMA', 11),
  (public.dev_seed_uuid('grade:XII'), public.dev_seed_uuid('tenant:sma-nusantara-dev'), 'XII', 'Kelas XII', 'SMA', 12)
ON CONFLICT (id) DO NOTHING;

-- ─── 3. Rombel (4 class-sections, wali_kelas assigned) ───────────────────────
INSERT INTO public.rombel (id, tenant_id, academic_year_id, grade_level_id, code, name, wali_kelas_id, capacity, status)
VALUES
  (public.dev_seed_uuid('rombel:X-IPA-1'),
   public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('ay:2026-2027'),
   public.dev_seed_uuid('grade:X'),
   'X-IPA-1', 'Kelas X IPA 1',
   public.dev_seed_uuid('user:wali.x-ipa-1@nusantara.dev'), 36, 'active'),
  (public.dev_seed_uuid('rombel:X-IPA-2'),
   public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('ay:2026-2027'),
   public.dev_seed_uuid('grade:X'),
   'X-IPA-2', 'Kelas X IPA 2',
   public.dev_seed_uuid('user:wali.x-ipa-2@nusantara.dev'), 36, 'active'),
  (public.dev_seed_uuid('rombel:X-IPS-1'),
   public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('ay:2026-2027'),
   public.dev_seed_uuid('grade:X'),
   'X-IPS-1', 'Kelas X IPS 1',
   public.dev_seed_uuid('user:wali.x-ips-1@nusantara.dev'), 36, 'active'),
  (public.dev_seed_uuid('rombel:XI-IPA-1'),
   public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('ay:2026-2027'),
   public.dev_seed_uuid('grade:XI'),
   'XI-IPA-1', 'Kelas XI IPA 1',
   public.dev_seed_uuid('user:wali.xi-ipa-1@nusantara.dev'), 36, 'active')
ON CONFLICT (id) DO NOTHING;

-- ─── 4. Rombel members (distribute 120 siswa into 4 rombel: 30/28/26/30) ─────
-- Siswa IDs generated by dev_seed.sql as user:siswa{NNN}@nusantara.dev
INSERT INTO public.rombel_members (id, tenant_id, rombel_id, student_id, joined_at)
SELECT
  public.dev_seed_uuid('rombel_member:' || cfg.rombel || ':' || n) AS id,
  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
  public.dev_seed_uuid('rombel:' || cfg.rombel),
  public.dev_seed_uuid('user:siswa' || lpad(n::text, 3, '0') || '@nusantara.dev'),
  now() - interval '60 days'
FROM (VALUES
  ('X-IPA-1',   1,  30),
  ('X-IPA-2',  31,  58),
  ('X-IPS-1',  59,  84),
  ('XI-IPA-1', 85, 114)
) AS cfg(rombel, range_lo, range_hi)
CROSS JOIN LATERAL generate_series(cfg.range_lo, cfg.range_hi) n
ON CONFLICT (id) DO NOTHING;

-- ─── 5. Subjects (9 mata pelajaran fase E SMA Kurmer) ─────────────────────────
INSERT INTO public.subjects (id, tenant_id, code, name, school_band, is_kurmer_phase, description)
VALUES
  (public.dev_seed_uuid('subj:MTK'),    public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'MTK',    'Matematika',         'SMA', 'E', 'Matematika fase E (kelas X)'),
  (public.dev_seed_uuid('subj:BIND'),   public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'BIND',   'Bahasa Indonesia',   'SMA', 'E', 'Bahasa Indonesia fase E'),
  (public.dev_seed_uuid('subj:BING'),   public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'BING',   'Bahasa Inggris',     'SMA', 'E', 'Bahasa Inggris fase E'),
  (public.dev_seed_uuid('subj:FISIKA'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'FISIKA', 'Fisika',             'SMA', 'E', 'Fisika fase E'),
  (public.dev_seed_uuid('subj:BIOLOGI'),public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'BIOLOGI','Biologi',            'SMA', 'E', 'Biologi fase E'),
  (public.dev_seed_uuid('subj:KIMIA'),  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'KIMIA',  'Kimia',              'SMA', 'E', 'Kimia fase E'),
  (public.dev_seed_uuid('subj:PKN'),    public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'PKN',    'Pendidikan Pancasila','SMA','E', 'Pendidikan Pancasila fase E'),
  (public.dev_seed_uuid('subj:SEJARAH'),public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'SEJARAH','Sejarah Indonesia',  'SMA', 'E', 'Sejarah Indonesia fase E'),
  (public.dev_seed_uuid('subj:PAI'),    public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   'PAI',    'Pendidikan Agama Islam','SMA','E','PAI fase E')
ON CONFLICT (id) DO NOTHING;

-- ─── 6. Curriculum items (CP samples for Matematika, Bahasa Indonesia, Fisika) ─
-- Representative sample; production sekolah load full CP set from Kemdikbud.
-- CP = Capaian Pembelajaran, ATP = Alur Tujuan Pembelajaran
INSERT INTO public.curriculum_items (id, tenant_id, subject_id, grade_level_id, code, item_type, title, description, sort_order)
VALUES
  -- Matematika
  (public.dev_seed_uuid('cp:mtk-bil'),  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:MTK'), public.dev_seed_uuid('grade:X'),
   'MTK.E.BIL', 'CP', 'Bilangan',
   'Menggeneralisasi sifat bilangan berpangkat, bentuk akar, dan logaritma', 10),
  (public.dev_seed_uuid('cp:mtk-alj'),  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:MTK'), public.dev_seed_uuid('grade:X'),
   'MTK.E.ALJ', 'CP', 'Aljabar',
   'Menyelesaikan sistem persamaan linear tiga variabel dan pertidaksamaan', 20),
  (public.dev_seed_uuid('cp:mtk-geo'),  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:MTK'), public.dev_seed_uuid('grade:X'),
   'MTK.E.GEO', 'CP', 'Geometri',
   'Menyelesaikan permasalahan segitiga menggunakan perbandingan trigonometri', 30),
  (public.dev_seed_uuid('cp:mtk-stat'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:MTK'), public.dev_seed_uuid('grade:X'),
   'MTK.E.STAT','CP', 'Statistika & Peluang',
   'Merangkum data dengan distribusi bivariat dan peluang kejadian majemuk', 40),
  -- Bahasa Indonesia
  (public.dev_seed_uuid('cp:bind-menyimak'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:BIND'), public.dev_seed_uuid('grade:X'),
   'BIND.E.MENYIMAK', 'CP', 'Menyimak',
   'Mengevaluasi informasi berupa gagasan dari teks lisan dan audiovisual', 10),
  (public.dev_seed_uuid('cp:bind-membaca'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:BIND'), public.dev_seed_uuid('grade:X'),
   'BIND.E.MEMBACA', 'CP', 'Membaca & Memirsa',
   'Mengevaluasi informasi dari teks eksplanasi, eksposisi, dan teks sastra', 20),
  (public.dev_seed_uuid('cp:bind-menulis'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:BIND'), public.dev_seed_uuid('grade:X'),
   'BIND.E.MENULIS', 'CP', 'Menulis',
   'Menulis gagasan, pikiran, pandangan dalam teks argumentatif dan naratif', 30),
  -- Fisika
  (public.dev_seed_uuid('cp:fis-pengukuran'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:FISIKA'), public.dev_seed_uuid('grade:X'),
   'FIS.E.PENGUKURAN', 'CP', 'Pengukuran & Besaran',
   'Menerapkan konsep pengukuran, ketidakpastian, dan angka penting', 10),
  (public.dev_seed_uuid('cp:fis-gerak'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:FISIKA'), public.dev_seed_uuid('grade:X'),
   'FIS.E.GERAK', 'CP', 'Gerak & Gaya',
   'Menganalisis gerak lurus, melingkar, dan hukum Newton', 20),
  (public.dev_seed_uuid('cp:fis-energi'), public.dev_seed_uuid('tenant:sma-nusantara-dev'),
   public.dev_seed_uuid('subj:FISIKA'), public.dev_seed_uuid('grade:X'),
   'FIS.E.ENERGI', 'CP', 'Energi & Momentum',
   'Menganalisis konsep energi, usaha, daya, dan kekekalan momentum', 30)
ON CONFLICT (id) DO NOTHING;

COMMIT;

-- ─── 7. Assignments (12 sample across 4 courses) ─────────────────────────────
BEGIN;
INSERT INTO public.assignments (id, tenant_id, course_id, class_id, title, description, due_date, created_at, updated_at)
SELECT
  public.dev_seed_uuid('assignment:' || cfg.course || ':' || cfg.n) AS id,
  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
  public.dev_seed_uuid('course:' || cfg.course),
  (SELECT id FROM public.classes WHERE tenant_id = public.dev_seed_uuid('tenant:sma-nusantara-dev') LIMIT 1),
  cfg.title,
  cfg.description,
  now() + (cfg.days_offset || ' days')::interval,
  now() - interval '14 days',
  now() - interval '14 days'
FROM (VALUES
  ('matematika-x', 1, 'Latihan Bilangan Berpangkat', 'Kerjakan soal 1-10 dari BAB 1', -7),
  ('matematika-x', 2, 'Ujian Harian Aljabar', 'Tes harian sistem persamaan linear', -1),
  ('matematika-x', 3, 'Proyek Mini: Grafik Fungsi', 'Gambar grafik fungsi kuadrat di GeoGebra', 7),
  ('bahasa-indonesia-x', 1, 'Menulis Esai Argumentatif', 'Topik: dampak media sosial', -5),
  ('bahasa-indonesia-x', 2, 'Presentasi Buku', 'Pilih 1 buku, ringkas + presentasi', 10),
  ('bahasa-indonesia-x', 3, 'Analisis Puisi', 'Analisis puisi Chairil Anwar', 14),
  ('fisika-x', 1, 'Laporan Praktikum Pengukuran', 'Laporan hasil praktikum jangka sorong', -3),
  ('fisika-x', 2, 'Soal Kinematika', 'Kerjakan soal gerak lurus halaman 45-47', 3),
  ('fisika-x', 3, 'Tugas Makalah Energi', 'Makalah 1500 kata tentang energi alternatif', 21),
  ('biologi-x', 1, 'Pengamatan Sel', 'Pengamatan sel tumbuhan & hewan di mikroskop', -2),
  ('biologi-x', 2, 'Kuis Jaringan Tumbuhan', 'Kuis pilihan ganda', 1),
  ('biologi-x', 3, 'Proyek Biodiversitas', 'Dokumentasi keragaman hayati sekitar rumah', 28)
) AS cfg(course, n, title, description, days_offset)
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ─── 8. Attendance (last 10 school days, 92% hadir rata-rata) ────────────────
-- Reproducible pseudo-random via hash of (date, student) modulo.
BEGIN;
INSERT INTO public.attendance_records (id, tenant_id, enrollment_id, date, status)
SELECT
  public.dev_seed_uuid('att:' || e.id || ':' || d.date) AS id,
  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
  e.id,
  d.date,
  CASE
    WHEN (('x' || substr(md5(e.id::text || d.date::text), 1, 8))::bit(32)::int) % 100 < 92 THEN 'PRESENT'::attendance_status
    WHEN (('x' || substr(md5(e.id::text || d.date::text), 1, 8))::bit(32)::int) % 100 < 96 THEN 'EXCUSED'::attendance_status
    WHEN (('x' || substr(md5(e.id::text || d.date::text), 1, 8))::bit(32)::int) % 100 < 98 THEN 'LATE'::attendance_status
    ELSE 'ABSENT'::attendance_status
  END
FROM public.enrollments e
CROSS JOIN (
  SELECT CURRENT_DATE - (n || ' days')::interval AS date
  FROM generate_series(1, 14) n
  WHERE EXTRACT(DOW FROM CURRENT_DATE - (n || ' days')::interval) BETWEEN 1 AND 5
) d
WHERE e.tenant_id = public.dev_seed_uuid('tenant:sma-nusantara-dev') AND e.status = 'ACTIVE'
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ─── 9. SPP Invoices (3 months × 120 students, 60% paid) ─────────────────────
BEGIN;
INSERT INTO public.invoices (id, tenant_id, student_id, amount, status, invoice_number, created_at, updated_at)
SELECT
  public.dev_seed_uuid('invoice:' || p.email || ':' || m) AS id,
  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
  p.id,
  500000.0,
  CASE
    WHEN (('x' || substr(md5(p.email || m::text), 1, 8))::bit(32)::int) % 100 < 60 THEN 'PAID'
    ELSE 'PENDING'
  END,
  'INV/' || to_char(now() - ((3 - m) || ' months')::interval, 'YYYYMM') || '/' || lpad(row_number() OVER (PARTITION BY m)::text, 4, '0'),
  now() - ((3 - m) || ' months')::interval,
  now() - ((3 - m) || ' months')::interval + interval '1 day'
FROM public.profiles p
CROSS JOIN generate_series(1, 3) m
WHERE p.tenant_id = public.dev_seed_uuid('tenant:sma-nusantara-dev')
  AND p.email LIKE 'siswa%@nusantara.dev'
ON CONFLICT (id) DO NOTHING;
COMMIT;

-- ─── 10. P5 Project (1 tema: Kewirausahaan) ──────────────────────────────────
BEGIN;
INSERT INTO public.p5_projects (id, tenant_id, academic_year_id, title, description,
                                 facilitator_id, starts_on, ends_on, status)
VALUES (
  public.dev_seed_uuid('p5:kewirausahaan-2026'),
  public.dev_seed_uuid('tenant:sma-nusantara-dev'),
  public.dev_seed_uuid('ay:2026-2027'),
  'Kewirausahaan: Dari Ide Jadi Produk',
  'Siswa merancang produk wirausaha berbasis kearifan lokal. Output: prototipe + rencana bisnis. Lintas mapel: PKn, Matematika, Bahasa Indonesia, Seni.',
  public.dev_seed_uuid('user:wakasek.kurikulum@nusantara.dev'),
  DATE '2026-10-01',
  DATE '2026-12-15',
  'active'
)
ON CONFLICT (id) DO NOTHING;
COMMIT;
