import {
  Home,
  LayoutGrid,
  GraduationCap,
  BookOpenCheck,
  Calendar,
  Megaphone,
  HelpCircle,
  UserCircle,
  FileText,
  Users,
  FolderKanban,
  Wallet,
  UserPlus,
  Building2,
  Sparkles,
  BarChart3,
  ScanFace,
  PenTool,
  MessageSquare,
  FileSignature,
  CreditCard,
  PlayCircle,
  Trophy,
  Award,
  Settings,
  Gamepad2,
  type LucideIcon,
} from 'lucide-react'

export interface NavItem {
  id: string
  name: string
  path: string
  icon: LucideIcon
  roles: string[]
  moduleId?: string
  location:
    | 'sidebar'
    | 'directory'
    | 'learning-hub'
    | 'teaching-hub'
    | 'social-hub'
    | 'gamification-hub'
    | 'admin-hub'
  description?: string
  color?: string
  bg?: string
  border?: string
  notification?: number
}

export const navigationItems: NavItem[] = [
  // --- SIDEBAR ITEMS (HUBS) ---

  // Teacher Sidebar
  {
    id: 'dashboard-teacher',
    name: 'Pusat Mengajar',
    path: '/teacher-dashboard',
    icon: GraduationCap,
    roles: ['teacher'],
    location: 'sidebar',
  },

  // Student Sidebar
  {
    id: 'ruang-belajar',
    name: 'Unified Learning Dashboard',
    path: '/',
    icon: Home,
    roles: ['student'],
    location: 'sidebar',
  },

  // Shared Sidebar
  {
    id: 'social-hub-link',
    name: 'Sosial & Info',
    path: '/social-hub',
    icon: Users,
    roles: ['teacher', 'student'],
    location: 'sidebar',
  },
  {
    id: 'gamification-hub-link',
    name: 'Gamifikasi',
    path: '/gamification-hub',
    icon: Gamepad2,
    roles: ['student'],
    location: 'sidebar',
  },
  {
    id: 'settings',
    name: 'Pengaturan',
    path: '/settings',
    icon: Settings,
    roles: ['teacher', 'student'],
    location: 'sidebar',
  },

  // Admin Sidebar
  {
    id: 'admin-hub-link',
    name: 'Administrasi',
    path: '/admin-hub',
    icon: Building2,
    roles: ['admin'],
    location: 'sidebar',
  },

  // --- HUB CONTENTS ---

  // Teaching Hub Items
  {
    id: 'course-builder',
    name: 'Manajemen Materi',
    path: '/teaching/course-builder',
    icon: LayoutGrid,
    roles: ['teacher'],
    location: 'teaching-hub',
    description: 'Atur modul, materi, dan alur belajar siswa.',
    color: 'text-violet-600',
    bg: 'bg-violet-100',
    border: 'border-violet-200',
  },
  {
    id: 'gradebook',
    name: 'Buku Nilai',
    path: '/gradebook',
    icon: BookOpenCheck,
    roles: ['teacher'],
    moduleId: 'gradebook',
    location: 'teaching-hub',
    description: 'Sistem pencatatan dan rekap nilai siswa.',
    color: 'text-blue-600',
    bg: 'bg-blue-100',
    border: 'border-blue-200',
    notification: 3,
  },
  {
    id: 'quiz-gradebook',
    name: 'Quiz Gradebook',
    path: '/teaching/quiz-gradebook',
    icon: BookOpenCheck,
    roles: ['teacher'],
    moduleId: 'quiz',
    location: 'teaching-hub',
    description: 'Rekap nilai dan statistik kuis otomatis.',
    color: 'text-emerald-600',
    bg: 'bg-emerald-100',
    border: 'border-emerald-200',
  },
  {
    id: 'quiz-manager',
    name: 'Manajemen Kuis',
    path: '/teaching/quiz-manager',
    icon: HelpCircle,
    roles: ['teacher'],
    moduleId: 'quiz',
    location: 'teaching-hub',
    description: 'Buat, kelola, dan publish kuis untuk kelas.',
    color: 'text-purple-600',
    bg: 'bg-purple-100',
    border: 'border-purple-200',
  },
  {
    id: 'assignment-gradebook',
    name: 'Assignment Gradebook',
    path: '/teaching/assignment-gradebook',
    icon: FileText,
    roles: ['teacher'],
    moduleId: 'assignments',
    location: 'teaching-hub',
    description: 'Nilai dan berikan umpan balik tugas siswa.',
    color: 'text-blue-600',
    bg: 'bg-blue-100',
    border: 'border-blue-200',
  },
  {
    id: 'ai-creator',
    name: 'AI Creator',
    path: '/creator',
    icon: Sparkles,
    roles: ['teacher'],
    moduleId: 'ai-creator',
    location: 'teaching-hub',
    description: 'Buat kuis & materi otomatis dari dokumen/video.',
    color: 'text-purple-600',
    bg: 'bg-purple-100',
    border: 'border-purple-200',
  },
  {
    id: 'analytics',
    name: 'Dasbor Analitik',
    path: '/analytics',
    icon: BarChart3,
    roles: ['teacher'],
    moduleId: 'analytics',
    location: 'teaching-hub',
    description: 'Visualisasi data & prediksi risiko siswa.',
    color: 'text-indigo-600',
    bg: 'bg-indigo-100',
    border: 'border-indigo-200',
  },
  {
    id: 'attendance',
    name: 'Scan Absensi',
    path: '/scan-attendance',
    icon: ScanFace,
    roles: ['teacher'],
    moduleId: 'attendance',
    location: 'teaching-hub',
    description: 'Scan otomatis buku absensi siswa menggunakan AI.',
    color: 'text-rose-600',
    bg: 'bg-rose-100',
    border: 'border-rose-200',
  },
  {
    id: 'grader',
    name: 'SpeedGrader',
    path: '/grader',
    icon: PenTool,
    roles: ['teacher'],
    moduleId: 'speed-grader',
    location: 'teaching-hub',
    description: 'Penilaian esai dengan matriks rubrik transparan.',
    color: 'text-amber-600',
    bg: 'bg-amber-100',
    border: 'border-amber-200',
  },
  {
    id: 'group-assignment-teacher',
    name: 'Tugas Kelompok',
    path: '/group-assignment',
    icon: Users,
    roles: ['teacher'],
    moduleId: 'group-assignment',
    location: 'teaching-hub',
    description: 'Kelola dan pantau tugas kolaborasi kelompok siswa.',
    color: 'text-indigo-600',
    bg: 'bg-indigo-100',
    border: 'border-indigo-200',
  },
  {
    id: 'leaderboard-teacher',
    name: 'Papan Peringkat',
    path: '/leaderboard',
    icon: Trophy,
    roles: ['teacher'],
    location: 'teaching-hub',
    description: 'Lihat peringkat XP dan poin siswa di kelas.',
    color: 'text-yellow-600',
    bg: 'bg-yellow-100',
    border: 'border-yellow-200',
  },

  // Learning Hub Items
  {
    id: 'lesson',
    name: 'Smart Player',
    path: '/lesson',
    icon: PlayCircle,
    roles: ['student'],
    location: 'learning-hub',
    description: 'Video & artikel dengan auto-completion tracking.',
    color: 'text-cyan-600',
    bg: 'bg-cyan-100',
    border: 'border-cyan-200',
  },
  {
    id: 'quiz',
    name: 'Kuis',
    path: '/quiz',
    icon: HelpCircle,
    roles: ['student'],
    moduleId: 'quiz',
    location: 'learning-hub',
    description: 'Kerjakan kuis dan ujian online.',
    color: 'text-emerald-600',
    bg: 'bg-emerald-100',
    border: 'border-emerald-200',
  },
  {
    id: 'assignments',
    name: 'Pusat Tugas',
    path: '/assignments',
    icon: FolderKanban,
    roles: ['teacher', 'student'],
    moduleId: 'assignments',
    location: 'learning-hub',
    description: 'Kumpulkan dan kelola tugas harian.',
    color: 'text-orange-600',
    bg: 'bg-orange-100',
    border: 'border-orange-200',
    notification: 2,
  },
  {
    id: 'assignments-teacher',
    name: 'Pusat Tugas',
    path: '/assignments',
    icon: FolderKanban,
    roles: ['teacher'],
    moduleId: 'assignments',
    location: 'teaching-hub',
    description: 'Kelola dan nilai tugas harian siswa.',
    color: 'text-orange-600',
    bg: 'bg-orange-100',
    border: 'border-orange-200',
    notification: 2,
  },
  {
    id: 'group-assignment',
    name: 'Tugas Kelompok',
    path: '/group-assignment',
    icon: Users,
    roles: ['teacher', 'student'],
    moduleId: 'group-assignment',
    location: 'learning-hub',
    description: 'Kolaborasi tugas kelompok.',
    color: 'text-indigo-600',
    bg: 'bg-indigo-100',
    border: 'border-indigo-200',
  },
  {
    id: 'grades-student',
    name: 'Nilai Saya',
    path: '/grades',
    icon: Trophy,
    roles: ['student'],
    location: 'learning-hub',
    description: 'Lihat nilai tugas dan simulasi proyeksi nilai akhir.',
    color: 'text-yellow-600',
    bg: 'bg-yellow-100',
    border: 'border-yellow-200',
  },
  {
    id: 'attendance-student',
    name: 'Kehadiran',
    path: '/attendance',
    icon: Calendar,
    roles: ['student'],
    location: 'learning-hub',
    description: 'Rekap kehadiran berdasarkan data absensi guru.',
    color: 'text-rose-600',
    bg: 'bg-rose-100',
    border: 'border-rose-200',
  },

  // Social Hub Items
  {
    id: 'forum',
    name: 'Forum Diskusi',
    path: '/forum',
    icon: MessageSquare,
    roles: ['teacher', 'student'],
    moduleId: 'forum',
    location: 'social-hub',
    description: 'Ruang tanya jawab dan kolaborasi sosial.',
    color: 'text-green-600',
    bg: 'bg-green-100',
    border: 'border-green-200',
  },
  {
    id: 'calendar',
    name: 'Jadwal',
    path: '/calendar',
    icon: Calendar,
    roles: ['teacher', 'student'],
    moduleId: 'calendar',
    location: 'social-hub',
    description: 'Jadwal pelajaran dan agenda akademik.',
    color: 'text-blue-600',
    bg: 'bg-blue-100',
    border: 'border-blue-200',
  },
  {
    id: 'announcements',
    name: 'Pengumuman',
    path: '/announcements',
    icon: Megaphone,
    roles: ['teacher', 'student'],
    moduleId: 'announcements',
    location: 'social-hub',
    description: 'Papan informasi dan berita sekolah.',
    color: 'text-red-600',
    bg: 'bg-red-100',
    border: 'border-red-200',
  },

  // Gamification Hub Items
  {
    id: 'leaderboard',
    name: 'Leaderboard',
    path: '/leaderboard',
    icon: Trophy,
    roles: ['student'],
    location: 'gamification-hub',
    description: 'Peringkat siswa, XP, dan liga gamifikasi.',
    color: 'text-yellow-600',
    bg: 'bg-yellow-100',
    border: 'border-yellow-200',
  },
  {
    id: 'certificates',
    name: 'Sertifikat',
    path: '/certificates',
    icon: Award,
    roles: ['student'],
    location: 'gamification-hub',
    description: 'Galeri sertifikat kelulusan dan pencapaian.',
    color: 'text-amber-600',
    bg: 'bg-amber-100',
    border: 'border-amber-200',
  },

  // Admin Hub Items
  {
    id: 'documents',
    name: 'Surat & Dokumen',
    path: '/documents',
    icon: FileSignature,
    roles: ['teacher', 'admin'],
    moduleId: 'documents',
    location: 'admin-hub',
    description: 'Smart editor & approval surat berjenjang.',
    color: 'text-orange-600',
    bg: 'bg-orange-100',
    border: 'border-orange-200',
  },
  {
    id: 'analytics',
    name: 'Analitik',
    path: '/admin/analytics',
    icon: BarChart3,
    roles: ['admin'],
    location: 'admin-hub',
    description: 'Dashboard analitik pembelajaran.',
    color: 'text-blue-600',
    bg: 'bg-blue-100',
    border: 'border-blue-200',
  },
  {
    id: 'finance',
    name: 'Keuangan & SPP',
    path: '/admin/finance',
    icon: Wallet,
    roles: ['admin'],
    location: 'admin-hub',
    description: 'Manajemen keuangan sekolah dan SPP.',
    color: 'text-emerald-600',
    bg: 'bg-emerald-100',
    border: 'border-emerald-200',
  },
  {
    id: 'ppdb',
    name: 'PPDB Online',
    path: '/admin/ppdb',
    icon: UserPlus,
    roles: ['admin'],
    location: 'admin-hub',
    description: 'Penerimaan Peserta Didik Baru.',
    color: 'text-cyan-600',
    bg: 'bg-cyan-100',
    border: 'border-cyan-200',
  },
  {
    id: 'administration',
    name: 'Administrasi',
    path: '/admin/administration',
    icon: Building2,
    roles: ['admin'],
    location: 'admin-hub',
    description: 'Pengaturan umum sekolah.',
    color: 'text-slate-600',
    bg: 'bg-slate-100',
    border: 'border-slate-200',
  },
  {
    id: 'billing',
    name: 'Tagihan Siswa',
    path: '/billing',
    icon: CreditCard,
    roles: ['admin'],
    location: 'admin-hub',
    description: 'Kelola tagihan dan riwayat pembayaran.',
    color: 'text-teal-600',
    bg: 'bg-teal-100',
    border: 'border-teal-200',
  },

  // Directory Only Items (Misc)
  {
    id: 'profile',
    name: 'Profil Pengguna',
    path: '/profile',
    icon: UserCircle,
    roles: ['teacher', 'student'],
    location: 'directory',
    description: 'Kelola informasi akun dan preferensi.',
    color: 'text-blue-600',
    bg: 'bg-blue-100',
    border: 'border-blue-200',
  },
  {
    id: 'settings',
    name: 'Pengaturan',
    path: '/settings',
    icon: Settings,
    roles: ['teacher', 'student'],
    location: 'directory',
    description: 'Konfigurasi aplikasi dan notifikasi.',
    color: 'text-slate-600',
    bg: 'bg-slate-100',
    border: 'border-slate-200',
  },
]
