import {
  Activity,
  Award,
  BarChart3,
  BookOpen,
  BookOpenCheck,
  Building2,
  Calendar,
  CalendarDays,
  CreditCard,
  DollarSign,
  FileSignature,
  FileText,
  FolderKanban,
  Gamepad2,
  GraduationCap,
  Grid3X3,
  HelpCircle,
  Home,
  LayoutDashboard,
  LayoutGrid,
  type LucideIcon,
  Megaphone,
  MessageSquare,
  PenTool,
  PlayCircle,
  Puzzle,
  ScanFace,
  School,
  Settings,
  Shield,
  Sparkles,
  Trophy,
  UserCircle,
  UserPlus,
  Users,
  Users2,
  Wallet,
} from "lucide-react";

export interface NavItem {
  id: string;
  name: string;
  path: string;
  icon: LucideIcon;
  roles: string[];
  moduleId?: string;
  location:
    | "sidebar"
    | "directory"
    | "learning-hub"
    | "teaching-hub"
    | "social-hub"
    | "gamification-hub"
    | "admin-hub";
  description?: string;
  color?: string;
  bg?: string;
  border?: string;
  notification?: number;
}

// ─── Admin Navigation Groups ──────────────────────────────────────────────────

export interface AdminNavItem {
  label: string;
  icon: LucideIcon;
  href: string;
  /** Optional badge text, e.g. "Segera" */
  badge?: string;
}

export interface AdminNavGroup {
  group: string;
  items: AdminNavItem[];
}

/**
 * Grouped admin sidebar navigation config.
 * Groups are collapsible and support active-state highlighting.
 */
export const adminNavGroups: AdminNavGroup[] = [
  {
    group: "navigation.adminGroups.main.title",
    items: [
      {
        label: "navigation.adminGroups.main.dashboard",
        icon: LayoutDashboard,
        href: "/app/admin/dashboard",
      },
      {
        label: "navigation.adminGroups.main.adminHub",
        icon: Grid3X3,
        href: "/app/admin/administration",
      },
    ],
  },
  {
    group: "navigation.adminGroups.usersClasses.title",
    items: [
      {
        label: "navigation.adminGroups.usersClasses.users",
        icon: Users,
        href: "/app/admin/users",
      },
      {
        label: "navigation.adminGroups.usersClasses.classes",
        icon: School,
        href: "/app/admin/classes",
      },
      {
        label: "navigation.adminGroups.usersClasses.courses",
        icon: BookOpen,
        href: "/app/admin/courses",
      },
    ],
  },
  {
    group: "navigation.adminGroups.academic.title",
    items: [
      {
        label: "navigation.adminGroups.academic.semester",
        icon: CalendarDays,
        href: "/app/admin/semester",
      },
    ],
  },
  {
    group: "navigation.adminGroups.finance.title",
    items: [
      {
        label: "navigation.adminGroups.finance.billing",
        icon: CreditCard,
        href: "/app/admin/billing",
      },
      {
        label: "navigation.adminGroups.finance.finance",
        icon: DollarSign,
        href: "/app/admin/finance",
      },
    ],
  },
  {
    group: "navigation.adminGroups.system.title",
    items: [
      {
        label: "navigation.adminGroups.system.systemHealth",
        icon: Activity,
        href: "/app/admin/system-health",
      },
      {
        label: "navigation.adminGroups.system.ltiIntegration",
        icon: Puzzle,
        href: "/admin/lti",
        badge: "Segera",
      },
      {
        label: "navigation.adminGroups.system.settings",
        icon: Settings,
        href: "/settings",
      },
    ],
  },
];

export const navigationItems: NavItem[] = [
  // --- SIDEBAR ITEMS (HUBS) ---

  // Teacher Sidebar
  {
    id: "dashboard-teacher",
    name: "navigation.items.dashboardTeacher.name",
    path: "/app/teacher/dashboard",
    icon: GraduationCap,
    roles: ["teacher"],
    location: "sidebar",
  },

  // Student Sidebar
  {
    id: "ruang-belajar",
    name: "navigation.items.ruangBelajar.name",
    path: "/app/student/dashboard",
    icon: Home,
    roles: ["student"],
    location: "sidebar",
  },

  // Shared Sidebar
  {
    id: "social-hub-link",
    name: "navigation.items.socialHubLink.name",
    path: "/social-hub",
    icon: Users,
    roles: ["teacher", "student"],
    location: "sidebar",
  },
  {
    id: "gamification-hub-link",
    name: "navigation.items.gamificationHubLink.name",
    path: "/gamification-hub",
    icon: Gamepad2,
    roles: ["student", "teacher"],
    location: "sidebar",
  },
  {
    id: "settings",
    name: "navigation.items.settings.name",
    path: "/settings",
    icon: Settings,
    roles: ["teacher", "student"],
    location: "sidebar",
  },

  // Admin Sidebar
  {
    id: "admin-hub-link",
    name: "navigation.items.adminHubLink.name",
    path: "/app/admin/dashboard",
    icon: Building2,
    roles: ["admin"],
    location: "sidebar",
  },
  {
    id: "admin-users-sidebar",
    name: "navigation.items.adminUsersSidebar.name",
    path: "/app/admin/users",
    icon: Users,
    roles: ["admin"],
    location: "sidebar",
  },
  {
    id: "admin-billing-sidebar",
    name: "navigation.items.adminBillingSidebar.name",
    path: "/app/admin/billing",
    icon: CreditCard,
    roles: ["admin"],
    location: "sidebar",
  },
  {
    id: "admin-settings-sidebar",
    name: "navigation.items.adminSettingsSidebar.name",
    path: "/settings",
    icon: Settings,
    roles: ["admin"],
    location: "sidebar",
  },

  // --- HUB CONTENTS ---

  // Teaching Hub Items
  {
    id: "course-builder",
    name: "navigation.items.courseBuilder.name",
    path: "/app/teacher/course-builder",
    icon: LayoutGrid,
    roles: ["teacher"],
    location: "teaching-hub",
    description: "navigation.items.courseBuilder.description",
    color: "text-violet-600",
    bg: "bg-violet-100",
    border: "border-violet-200",
  },
  {
    id: "gradebook",
    name: "navigation.items.gradebook.name",
    path: "/app/teacher/gradebook",
    icon: BookOpenCheck,
    roles: ["teacher"],
    moduleId: "gradebook",
    location: "teaching-hub",
    description: "navigation.items.gradebook.description",
    color: "text-blue-600",
    bg: "bg-blue-100",
    border: "border-blue-200",
    notification: 3,
  },
  {
    id: "quiz-gradebook",
    name: "navigation.items.quizGradebook.name",
    path: "/app/teacher/quiz-gradebook",
    icon: BookOpenCheck,
    roles: ["teacher"],
    moduleId: "quiz",
    location: "teaching-hub",
    description: "navigation.items.quizGradebook.description",
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    border: "border-emerald-200",
  },
  {
    id: "quiz-manager",
    name: "navigation.items.quizManager.name",
    path: "/app/teacher/quiz-manager",
    icon: HelpCircle,
    roles: ["teacher"],
    moduleId: "quiz",
    location: "teaching-hub",
    description: "navigation.items.quizManager.description",
    color: "text-purple-600",
    bg: "bg-purple-100",
    border: "border-purple-200",
  },
  {
    id: "assignment-gradebook",
    name: "navigation.items.assignmentGradebook.name",
    path: "/app/teacher/assignment-gradebook",
    icon: FileText,
    roles: ["teacher"],
    moduleId: "assignments",
    location: "teaching-hub",
    description: "navigation.items.assignmentGradebook.description",
    color: "text-blue-600",
    bg: "bg-blue-100",
    border: "border-blue-200",
  },
  {
    id: "ai-creator",
    name: "navigation.items.aiCreator.name",
    path: "/app/teacher/creator",
    icon: Sparkles,
    roles: ["teacher"],
    moduleId: "ai-creator",
    location: "teaching-hub",
    description: "navigation.items.aiCreator.description",
    color: "text-purple-600",
    bg: "bg-purple-100",
    border: "border-purple-200",
  },
  {
    id: "analytics",
    name: "navigation.items.analytics.name",
    path: "/app/teacher/analytics",
    icon: BarChart3,
    roles: ["teacher"],
    moduleId: "analytics",
    location: "teaching-hub",
    description: "navigation.items.analytics.description",
    color: "text-indigo-600",
    bg: "bg-indigo-100",
    border: "border-indigo-200",
  },
  {
    id: "lesson-monitor",
    name: "navigation.items.lessonMonitor.name",
    path: "/app/teacher/lesson-monitor",
    icon: Activity,
    roles: ["teacher"],
    location: "teaching-hub",
    description: "navigation.items.lessonMonitor.description",
    color: "text-red-600",
    bg: "bg-red-100",
    border: "border-red-200",
  },
  {
    id: "attendance",
    name: "navigation.items.attendance.name",
    path: "/app/teacher/scan-attendance",
    icon: ScanFace,
    roles: ["teacher"],
    moduleId: "attendance",
    location: "teaching-hub",
    description: "navigation.items.attendance.description",
    color: "text-rose-600",
    bg: "bg-rose-100",
    border: "border-rose-200",
  },
  {
    id: "grader",
    name: "navigation.items.grader.name",
    path: "/app/teacher/grader",
    icon: PenTool,
    roles: ["teacher"],
    moduleId: "speed-grader",
    location: "teaching-hub",
    description: "navigation.items.grader.description",
    color: "text-amber-600",
    bg: "bg-amber-100",
    border: "border-amber-200",
  },
  {
    id: "group-assignment-teacher",
    name: "navigation.items.groupAssignmentTeacher.name",
    path: "/group-assignment",
    icon: Users,
    roles: ["teacher"],
    moduleId: "group-assignment",
    location: "teaching-hub",
    description: "navigation.items.groupAssignmentTeacher.description",
    color: "text-indigo-600",
    bg: "bg-indigo-100",
    border: "border-indigo-200",
  },
  {
    id: "leaderboard-teacher",
    name: "navigation.items.leaderboardTeacher.name",
    path: "/app/teacher/leaderboard",
    icon: Trophy,
    roles: ["teacher"],
    location: "teaching-hub",
    description: "navigation.items.leaderboardTeacher.description",
    color: "text-yellow-600",
    bg: "bg-yellow-100",
    border: "border-yellow-200",
  },

  // Learning Hub Items
  {
    id: "lesson",
    name: "navigation.items.lesson.name",
    path: "/lesson",
    icon: PlayCircle,
    roles: ["student"],
    location: "learning-hub",
    description: "navigation.items.lesson.description",
    color: "text-cyan-600",
    bg: "bg-cyan-100",
    border: "border-cyan-200",
  },
  {
    id: "quiz",
    name: "navigation.items.quiz.name",
    path: "/quiz",
    icon: HelpCircle,
    roles: ["student"],
    moduleId: "quiz",
    location: "learning-hub",
    description: "navigation.items.quiz.description",
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    border: "border-emerald-200",
  },
  {
    id: "assignments",
    name: "navigation.items.assignments.name",
    path: "/assignments",
    icon: FolderKanban,
    roles: ["teacher", "student"],
    moduleId: "assignments",
    location: "learning-hub",
    description: "navigation.items.assignments.description",
    color: "text-orange-600",
    bg: "bg-orange-100",
    border: "border-orange-200",
    notification: 2,
  },
  {
    id: "assignments-teacher",
    name: "navigation.items.assignmentsTeacher.name",
    path: "/assignments",
    icon: FolderKanban,
    roles: ["teacher"],
    moduleId: "assignments",
    location: "teaching-hub",
    description: "navigation.items.assignmentsTeacher.description",
    color: "text-orange-600",
    bg: "bg-orange-100",
    border: "border-orange-200",
    notification: 2,
  },
  {
    id: "group-assignment",
    name: "navigation.items.groupAssignment.name",
    path: "/group-assignment",
    icon: Users,
    roles: ["teacher", "student"],
    moduleId: "group-assignment",
    location: "learning-hub",
    description: "navigation.items.groupAssignment.description",
    color: "text-indigo-600",
    bg: "bg-indigo-100",
    border: "border-indigo-200",
  },
  {
    id: "grades-student",
    name: "navigation.items.gradesStudent.name",
    path: "/grades",
    icon: Trophy,
    roles: ["student"],
    location: "learning-hub",
    description: "navigation.items.gradesStudent.description",
    color: "text-yellow-600",
    bg: "bg-yellow-100",
    border: "border-yellow-200",
  },
  {
    id: "attendance-student",
    name: "navigation.items.attendanceStudent.name",
    path: "/attendance",
    icon: Calendar,
    roles: ["student"],
    location: "learning-hub",
    description: "navigation.items.attendanceStudent.description",
    color: "text-rose-600",
    bg: "bg-rose-100",
    border: "border-rose-200",
  },
  {
    id: "peer-review",
    name: "navigation.items.peerReview.name",
    path: "/app/student/peer-reviews",
    icon: Users2,
    roles: ["student"],
    moduleId: "peer-review",
    location: "learning-hub",
    description: "navigation.items.peerReview.description",
    color: "text-violet-600",
    bg: "bg-violet-100",
    border: "border-violet-200",
  },

  // Social Hub Items
  {
    id: "forum",
    name: "navigation.items.forum.name",
    path: "/forum",
    icon: MessageSquare,
    roles: ["teacher", "student"],
    moduleId: "forum",
    location: "social-hub",
    description: "navigation.items.forum.description",
    color: "text-green-600",
    bg: "bg-green-100",
    border: "border-green-200",
  },
  {
    id: "calendar",
    name: "navigation.items.calendar.name",
    path: "/calendar",
    icon: Calendar,
    roles: ["teacher", "student"],
    moduleId: "calendar",
    location: "social-hub",
    description: "navigation.items.calendar.description",
    color: "text-blue-600",
    bg: "bg-blue-100",
    border: "border-blue-200",
  },
  {
    id: "announcements",
    name: "navigation.items.announcements.name",
    path: "/announcements",
    icon: Megaphone,
    roles: ["teacher", "student"],
    moduleId: "announcements",
    location: "social-hub",
    description: "navigation.items.announcements.description",
    color: "text-red-600",
    bg: "bg-red-100",
    border: "border-red-200",
  },

  // Gamification Hub Items
  {
    id: "leaderboard",
    name: "navigation.items.leaderboard.name",
    path: "/leaderboard",
    icon: Trophy,
    roles: ["student", "teacher"],
    location: "gamification-hub",
    description: "navigation.items.leaderboard.description",
    color: "text-yellow-600",
    bg: "bg-yellow-100",
    border: "border-yellow-200",
  },
  {
    id: "certificates",
    name: "navigation.items.certificates.name",
    path: "/certificates",
    icon: Award,
    roles: ["student"],
    location: "gamification-hub",
    description: "navigation.items.certificates.description",
    color: "text-amber-600",
    bg: "bg-amber-100",
    border: "border-amber-200",
  },

  // Admin Hub Items
  {
    id: "documents",
    name: "navigation.items.documents.name",
    path: "/documents",
    icon: FileSignature,
    roles: ["teacher", "admin"],
    moduleId: "documents",
    location: "admin-hub",
    description: "navigation.items.documents.description",
    color: "text-orange-600",
    bg: "bg-orange-100",
    border: "border-orange-200",
  },
  {
    id: "admin-analytics",
    name: "navigation.items.adminAnalytics.name",
    path: "/app/admin/analytics",
    icon: BarChart3,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.adminAnalytics.description",
    color: "text-blue-600",
    bg: "bg-blue-100",
    border: "border-blue-200",
  },
  {
    id: "finance",
    name: "navigation.items.finance.name",
    path: "/app/admin/finance",
    icon: Wallet,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.finance.description",
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    border: "border-emerald-200",
  },
  {
    id: "ppdb",
    name: "navigation.items.ppdb.name",
    path: "/app/admin/ppdb",
    icon: UserPlus,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.ppdb.description",
    color: "text-cyan-600",
    bg: "bg-cyan-100",
    border: "border-cyan-200",
  },
  {
    id: "administration",
    name: "navigation.items.administration.name",
    path: "/app/admin/administration",
    icon: Building2,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.administration.description",
    color: "text-slate-600",
    bg: "bg-slate-100",
    border: "border-slate-200",
  },
  {
    id: "billing",
    name: "navigation.items.billing.name",
    path: "/app/admin/billing",
    icon: CreditCard,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.billing.description",
    color: "text-teal-600",
    bg: "bg-teal-100",
    border: "border-teal-200",
  },
  {
    id: "lti-management",
    name: "navigation.items.ltiManagement.name",
    path: "/admin/lti",
    icon: Shield,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.ltiManagement.description",
    color: "text-indigo-600",
    bg: "bg-indigo-100",
    border: "border-indigo-200",
  },

  // Directory Only Items (Misc)
  {
    id: "profile",
    name: "navigation.items.profile.name",
    path: "/profile",
    icon: UserCircle,
    roles: ["teacher", "student"],
    location: "directory",
    description: "navigation.items.profile.description",
    color: "text-blue-600",
    bg: "bg-blue-100",
    border: "border-blue-200",
  },
  {
    id: "settings-dir",
    name: "navigation.items.settingsDir.name",
    path: "/settings",
    icon: Settings,
    roles: ["teacher", "student"],
    location: "directory",
    description: "navigation.items.settingsDir.description",
    color: "text-slate-600",
    bg: "bg-slate-100",
    border: "border-slate-200",
  },
  {
    id: "semester-management",
    name: "navigation.items.semesterManagement.name",
    path: "/app/admin/semester",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.semesterManagement.description",
    color: "text-indigo-600",
    bg: "bg-indigo-100",
    border: "border-indigo-200",
  },
  {
    id: "academic-years",
    name: "navigation.items.academicYears.name",
    path: "/app/admin/academic-years",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.academicYears.description",
    color: "text-blue-600",
    bg: "bg-blue-100",
    border: "border-blue-200",
  },
  {
    id: "rombel-management",
    name: "navigation.items.rombelManagement.name",
    path: "/app/admin/rombel",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.rombelManagement.description",
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    border: "border-emerald-200",
  },
  {
    id: "subjects-management",
    name: "navigation.items.subjectsManagement.name",
    path: "/app/admin/subjects",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.subjectsManagement.description",
    color: "text-violet-600",
    bg: "bg-violet-100",
    border: "border-violet-200",
  },
  {
    id: "timetable-management",
    name: "navigation.items.timetableManagement.name",
    path: "/app/admin/timetable",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.timetableManagement.description",
    color: "text-sky-600",
    bg: "bg-sky-100",
    border: "border-sky-200",
  },
  {
    id: "rapor-kurmer",
    name: "navigation.items.raporKurmer.name",
    path: "/app/admin/rapor",
    icon: CalendarDays,
    roles: ["admin", "principal", "teacher"],
    location: "admin-hub",
    description: "navigation.items.raporKurmer.description",
    color: "text-indigo-600",
    bg: "bg-indigo-100",
    border: "border-indigo-200",
  },
  {
    id: "bos-tracking",
    name: "navigation.items.bosTracking.name",
    path: "/app/admin/bos",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.bosTracking.description",
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    border: "border-emerald-200",
  },
  {
    id: "ppdb-jalur",
    name: "navigation.items.ppdbJalur.name",
    path: "/app/admin/ppdb-jalur",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.ppdbJalur.description",
    color: "text-rose-600",
    bg: "bg-rose-100",
    border: "border-rose-200",
  },
  {
    id: "p5-projects",
    name: "navigation.items.p5Projects.name",
    path: "/app/admin/p5",
    icon: CalendarDays,
    roles: ["admin", "teacher"],
    location: "admin-hub",
    description: "navigation.items.p5Projects.description",
    color: "text-amber-600",
    bg: "bg-amber-100",
    border: "border-amber-200",
  },
  {
    id: "integrations",
    name: "navigation.items.integrations.name",
    path: "/app/admin/integrations",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.integrations.description",
    color: "text-purple-600",
    bg: "bg-purple-100",
    border: "border-purple-200",
  },
  {
    id: "principal-insights",
    name: "navigation.items.principalInsights.name",
    path: "/app/admin/insights",
    icon: CalendarDays,
    roles: ["admin", "principal"],
    location: "admin-hub",
    description: "navigation.items.principalInsights.description",
    color: "text-yellow-600",
    bg: "bg-yellow-100",
    border: "border-yellow-200",
  },
  {
    id: "counseling-notes",
    name: "navigation.items.counselingNotes.name",
    path: "/app/teacher/counseling",
    icon: CalendarDays,
    roles: ["teacher", "admin"],
    location: "teaching-hub",
    description: "navigation.items.counselingNotes.description",
    color: "text-pink-600",
    bg: "bg-pink-100",
    border: "border-pink-200",
  },
  {
    id: "akm-stimuli",
    name: "navigation.items.akmStimuli.name",
    path: "/app/admin/akm-stimuli",
    icon: CalendarDays,
    roles: ["admin", "teacher"],
    location: "admin-hub",
    description: "navigation.items.akmStimuli.description",
    color: "text-cyan-600",
    bg: "bg-cyan-100",
    border: "border-cyan-200",
  },
  {
    id: "bank-va",
    name: "navigation.items.bankVa.name",
    path: "/app/admin/bank-va",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.bankVa.description",
    color: "text-blue-700",
    bg: "bg-blue-100",
    border: "border-blue-200",
  },
  {
    id: "parent-links",
    name: "navigation.items.parentLinks.name",
    path: "/app/admin/parent-links",
    icon: CalendarDays,
    roles: ["admin"],
    location: "admin-hub",
    description: "navigation.items.parentLinks.description",
    color: "text-orange-600",
    bg: "bg-orange-100",
    border: "border-orange-200",
  },
  {
    id: "semantic-search",
    name: "navigation.items.semanticSearch.name",
    path: "/app/admin/search",
    icon: CalendarDays,
    roles: ["admin", "teacher", "principal"],
    location: "admin-hub",
    description: "navigation.items.semanticSearch.description",
    color: "text-violet-600",
    bg: "bg-violet-100",
    border: "border-violet-200",
  },
  {
    id: "rombel-attendance",
    name: "navigation.items.rombelAttendance.name",
    path: "/app/teacher/rombel-attendance",
    icon: CalendarDays,
    roles: ["teacher", "admin"],
    location: "teaching-hub",
    description: "navigation.items.rombelAttendance.description",
    color: "text-emerald-600",
    bg: "bg-emerald-100",
    border: "border-emerald-200",
  },
];
